### ISSUE TITLE
module_path should automatically try $XDG_DATA_HOME/weboob/modules/version

### ISSUE THREAD

**Issue by bagage** [Phyks/Flatisfy#6]
It would be convenient if module_path could automatically search for weboob modules in `$XDG_DATA_HOME/share/weboob/modules/$WEBOOB_VERSION` because, I expect, it's where modules will be installed by default / most of the time.

PS : also a nice notice in case of "weboob module could not be found" exception would be good to help the user fix the issue.

**Comment by Phyks** [comment]
Hmm, I'll give a look but I am not sure this is feasible. First of all, I think there are not all the available modules in `$XDG_DATA_HOME/share/weboob/modules/$WEBOOB_VERSION`, but only the ones that have a backend loaded in `Weboob` (through CLI). Then, I am not sure I can retrieve programatically the current Weboob version.

Additionally, urrent behavior is that if `modules_path` is `null`, it uses the Weboob internal loading mechanism, looking for [`modules` package](https://git.weboob.org/weboob/modules). If a path is provided, it uses this path. Then, I'm not sure of the best way to add such a mechanism. Maybe with an empty string, rather than `null`. But that can get quite confusing for the user :/

> PS : also a nice notice in case of "weboob module could not be found" exception would be good to help the user fix the issue.

What kind of notice would you like?
